FROM node:20-alpine

WORKDIR /app/apps/web

# Install dependencies (cached)
COPY apps/web/package.json ./
RUN npm install

# Copy project files
COPY apps/web ./

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
ENV NODE_ENV=development
ENV WATCHPACK_POLLING=true

EXPOSE 3000

CMD ["npm", "run", "dev"]
